In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("100_Unique_QA_Dataset.csv")

In [3]:
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [4]:
# Step 1: Tokenization --> Convert words to tokens
def tokenize(text):
  text = text.lower()
  text = text.replace('?', '') # replace special character ? with nothing
  text = text.replace("'", '')
  return text.split()

In [13]:
tokenize(df['question'][0])

['what', 'is', 'the', 'capital', 'of', 'france']

In [14]:
# Step 2: Create Vocabulary
vocab = {'<UNK>': 0}

In [26]:
def build_vocab(row):
  tokenized_question = tokenize(row['question'])
  tokenized_answer = tokenize(row['answer'])
  merged_tokens = tokenized_question + tokenized_answer
  #print(merged_tokens)
  for token in merged_tokens:
    if token not in vocab:
      vocab[token] = len(vocab)

In [27]:
df.apply(build_vocab, axis = 1)

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [28]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299,792,458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 'starry': 130,
 'night': 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'step': 143,
 'moon': 144,
 'armstrong': 145,
 'main': 146,
 'ingredient': 147,
 'guacamole': 148,
 'avocado': 149,
 'sides': 150,
 'does': 151,
 'hexagon': 152,
 'have': 153,
 '6': 154,
 'china': 155,
 'yuan': 156,
 'pride': 157,
 'and': 158,
 'prejudice': 159,
 'jane-austen': 160,
 'iron': 161,
 'fe': 162,
 'hardest': 163,
 'natural': 164,
 'substance': 165,
 'diamond': 166,
 'continent': 167,
 'by': 168,
 'area': 169,
 'asia': 170,
 'president': 171,
 'states': 172,
 'george-washington': 173,
 'bird': 174,
 'its': 175,
 'ability': 176,
 'mimic': 177,
 'sounds': 178,
 'parrot': 179,
 'longest-running': 180,
 'animated': 181,
 'tv': 182,
 'show': 183,
 'simpsons': 184,
 'vaticancity': 185,
 'most': 186,
 'moons': 187,
 'saturn': 188,
 'romeo': 189,
 'juliet': 190,
 'shakespeare': 191,
 'earths': 192,
 'atmosphere': 193,
 'nitrogen': 194,
 'bones': 195,
 'adult': 196,
 'human': 197,
 'body': 198,
 '206': 199,
 'metal': 200,
 'liquid': 201,
 'at': 202,
 'room': 203,
 'temperature': 204,
 'mercury': 205,
 'russia': 206,
 'moscow': 207,
 'electricity': 208,
 'benjamin-franklin': 209,
 'second-largest': 210,
 'land': 211,
 'color': 212,
 'ripe': 213,
 'banana': 214,
 'yellow': 215,
 'month': 216,
 '28': 217,
 'days': 218,
 'common': 219,
 'february': 220,
 'study': 221,
 'living': 222,
 'organisms': 223,
 'called': 224,
 'biology': 225,
 'home': 226,
 'great': 227,
 'wall': 228,
 'bees': 229,
 'collect': 230,
 'from': 231,
 'flowers': 232,
 'nectar': 233,
 'opposite': 234,
 'day': 235,
 'south': 236,
 'korea': 237,
 'seoul': 238,
 'bulb': 239,
 'edison': 240,
 'humans': 241,
 'breathe': 242,
 'survival': 243,
 'oxygen': 244,
 '144': 245,
 '12': 246,
 'pyramids': 247,
 'giza': 248,
 'egypt': 249,
 'sea': 250,
 'creature': 251,
 'eight': 252,
 'arms': 253,
 'octopus': 254,
 'holiday': 255,
 'celebrated': 256,
 'december': 257,
 '25': 258,
 'christmas': 259,
 'yen': 260,
 'legs': 261,
 'spider': 262,
 'sport': 263,
 'uses': 264,
 'net,': 265,
 'ball,': 266,
 'hoop': 267,
 'basketball': 268,
 'kangaroos': 269,
 'female': 270,
 'minister': 271,
 'uk': 272,
 'margaretthatcher': 273,
 'fastest': 274,
 'animal': 275,
 'cheetah': 276,
 'periodic': 277,
 'table': 278,
 'spain': 279,
 'madrid': 280,
 'closest': 281,
 'sun': 282,
 'father': 283,
 'computers': 284,
 'charlesbabbage': 285,
 'mexico': 286,
 'mexicocity': 287,
 'colors': 288,
 'rainbow': 289,
 'musical': 290,
 'instrument': 291,
 'black': 292,
 'white': 293,
 'keys': 294,
 'piano': 295,
 'americas': 296,
 '1492': 297,
 'christophercolumbus': 298,
 'disney': 299,
 'character': 300,
 'long': 301,
 'nose': 302,
 'grows': 303,
 'it': 304,
 'when': 305,
 'lying': 306,
 'pinocchio': 307,
 'directed': 308,
 'movie': 309,
 'titanic': 310,
 'jamescameron': 311,
 'superhero': 312,
 'also': 313,
 'dark': 314,
 'knight': 315,
 'batman': 316,
 'brasilia': 317,
 'fruit': 318,
 'king': 319,
 'fruits': 320,
 'mango': 321,
 'eiffel': 322,
 'tower': 323}

In [29]:
len(vocab)

324

In [35]:
# Convert word to Numerical Indices
def text_to_indices(text, vocab):
  indexed_text = []
  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token])
    else:
      indexed_text.append(vocab['<UNK>'])
  return indexed_text

In [36]:
text_to_indices("What is Anirban.", vocab)

[1, 2, 0]

In [38]:
import torch
from torch.utils.data import Dataset, DataLoader

In [42]:
class QADataset(Dataset):
  def __init__(self, df, vocab):
    self.df = df
    self.vocab = vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self, index):
    numerical_question = text_to_indices(self.df.iloc[index]['question'], self.vocab)
    numerical_answer = text_to_indices(self.df.iloc[index]['answer'], self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [43]:
dataset = QADataset(df, vocab)

In [44]:
dataset[10] # 10 row data ques, ans

(tensor([ 1,  2,  3,  4,  5, 53]), tensor([54]))

In [45]:
dataloader = DataLoader(dataset, batch_size = 1, shuffle = True) # since batch_size = 1 so no need to pad

In [46]:
for question, answer in dataloader:
  print(question, answer)

tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([[23]])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([[205]])
tensor([[10, 29,  3, 30, 31]]) tensor([[32]])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([[85]])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([[61]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([[124]])
tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]]) tensor([[155]])
tensor([[ 10,  75, 208]]) tensor([[209]])
tensor([[ 10,  11, 189, 158, 190]]) tensor([[191]])
tensor([[  1,   2,   3,  69,   5, 155]]) tensor([[156]])
tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]]) tensor([[285]])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([[199]])
tensor([[ 42, 101,   2,   3,  17]]) tensor([[102]])
tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([[36]])
tensor([[ 78,  79, 288,  81,  19,  14, 289]]) tensor([[85]])
tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]]) tensor([[307]])
tensor([[10, 96,  3, 97]]) tensor([[98]])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([[317]])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([[54]])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([[128]])
tensor([[ 42, 137,   2, 138,  39, 175, 269]]) tensor([[99]])
tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]]) tensor([[6]])
tensor([[ 42, 137, 118,   3, 247,   5, 248]]) tensor([[249]])
tensor([[  1,   2,   3,  37,  38,  39, 161]]) tensor([[162]])
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]) tensor([[244]])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([[145]])
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]) tensor([[268]])
tensor([[  1,   2,   3,   4,   5, 206]]) tensor([[207]])
tensor([[ 10,  29, 130, 131]]) tensor([[132]])
tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]]) tensor([[321]])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([[134]])
tensor([[ 42, 250, 251, 118, 252, 253]]) tensor([[254]])
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]) tensor([[225]])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([[65]])
tensor([[  1,   2,   3, 180, 181, 182, 183]]) tensor([[184]])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([[238]])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]) tensor([[166]])
tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]) tensor([[273]])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([[116]])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([[136]])
tensor([[10, 75, 76]]) tensor([[77]])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([[36]])
tensor([[ 10, 308,   3, 309, 310]]) tensor([[311]])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([[100]])
tensor([[  1,   2,   3, 146, 147,  19, 148]]) tensor([[149]])
tensor([[ 10,  96,   3, 104, 239]]) tensor([[240]])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([[72]])
tensor([[ 10,  11, 157, 158, 159]]) tensor([[160]])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([[53]])
tensor([[  1,   2,   3, 234,   5, 235]]) tensor([[131]])
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([[280]])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([[260]])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([[91]])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([[41]])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([[185]])
tensor([[  1,   2,   3,  33,  34,   5, 245]]) tensor([[246]])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([[295]])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([[52]])
tensor([[ 42, 255,   2, 256,  83, 257, 258]]) tensor([[259]])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([[74]])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([[58]])
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]) tensor([[121]])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([[215]])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([[106]])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([[194]])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([[28]])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([[121]])
tensor([[ 10,  75, 111]]) tensor([[112]])
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([[170]])
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([[276]])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([[110]])
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]) tensor([[205]])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([[179]])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([[7]])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([[68]])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([[9]])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([[36]])
tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([[316]])
tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]]) tensor([[220]])
tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]]) tensor([[113]])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([[95]])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([[49]])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([[16]])
tensor([[ 78,  79, 150, 151,  14, 152, 153]]) tensor([[154]])
tensor([[ 10,  75,   3, 296,  19, 297]]) tensor([[298]])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([[114]])
tensor([[  1,  87, 229, 230, 231, 232]]) tensor([[233]])
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]) tensor([[173]])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([[287]])
tensor([[ 42,  18, 118,   3, 186, 187]]) tensor([[188]])

### RNN Architecture
- 1 Input Layer $\rightarrow$ 50 dimensional word embedding vector
- 1 Hidden Layer $\rightarrow$ 64 neurons
- 1 Output Layer $\rightarrow$ 324 Neurons $\rightarrow$ equal to length of vocab

In [47]:
import torch.nn as nn

In [84]:
class SimpleRNN(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim = 50)
    self.rnn = nn.RNN(50, 64, batch_first = True)
    # we cant use Sequential() because from RNN layer we are getting multiple outputs (from Hidden States Oi and Final output)
    self.fc = nn.Linear(64, vocab_size)

  def forward(self, question):
    embedded_question = self.embedding(question)
    hidden, final = self.rnn(embedded_question)
    output = self.fc(final.squeeze(0))
    return output

In [53]:
# what does embedding layer do
x = nn.Embedding(324, embedding_dim = 50)
a = x(dataset[0][0]) # 0th row question
print(a)
# We get 6 vectors (number of words = 6) each of dimension 50

tensor([[-2.7905e-01,  6.2512e-01,  1.4794e+00,  1.0353e+00,  9.1692e-02,
         -7.8963e-01, -1.8489e+00, -2.1390e+00, -4.1245e-02, -7.4883e-01,
         -9.2151e-01,  2.3164e+00,  1.4413e+00, -8.1684e-01, -7.9389e-01,
          1.0044e+00, -1.0133e+00,  7.1586e-01,  9.9728e-01,  7.6236e-01,
          1.1985e+00, -5.9986e-01, -8.4827e-01, -1.4747e+00, -1.8072e-01,
          1.8730e+00,  8.2530e-01, -1.3752e+00, -1.9957e+00, -5.3346e-01,
          6.9772e-02,  1.2872e+00,  5.9771e-01,  1.5885e+00, -2.8372e-02,
          8.4699e-02, -1.4164e+00, -6.0629e-01, -2.8715e-01, -4.1684e-01,
          9.5565e-02, -4.0339e-01, -9.6968e-01,  3.9930e-01,  3.7131e-01,
         -7.6722e-01, -4.5726e-01, -1.8362e-01,  1.8718e-02,  2.6434e+00],
        [ 8.7164e-01,  1.2764e+00, -1.0232e+00, -4.4587e-01,  7.0637e-01,
         -1.1038e-01,  2.1126e-01, -9.3152e-01,  1.2357e-01, -4.2788e-01,
          5.7965e-01,  1.1039e+00, -2.2819e+00,  1.5913e-01, -2.3811e+00,
         -3.9384e-01, -3.3723e-01, -2.4482e-01, -7.3445e-01,  1.0173e+00,
          4.6116e-02, -6.6556e-01,  9.1768e-01,  4.0286e-01,  7.7650e-01,
          1.4173e+00, -2.2485e+00,  4.7164e-01, -3.9344e-01,  2.1377e-01,
          6.9925e-01, -1.3125e+00, -2.0981e+00,  7.3779e-01,  2.2357e+00,
          7.9066e-01, -1.2992e+00, -1.2357e+00,  2.0830e+00,  7.5003e-02,
         -1.3432e+00, -1.4248e+00,  7.5567e-01,  6.3158e-01, -2.7140e-01,
          7.1785e-01, -1.5396e+00, -3.4790e-01,  7.3502e-01, -1.3223e+00],
        [ 1.0157e+00, -1.8505e+00,  3.8316e-01,  2.1948e-02,  1.1145e+00,
          4.6061e-01,  6.8084e-01,  3.7325e-01, -7.5438e-01,  2.3032e-01,
          4.1588e-01,  2.5572e-02, -1.1494e+00, -6.1261e-01, -1.0582e-01,
         -5.5486e-01,  1.8119e+00,  7.0728e-02, -1.2975e+00,  1.6853e+00,
          1.9945e+00,  1.3462e-01,  4.0375e-01,  2.1062e+00, -1.1709e-01,
         -1.8830e-01, -2.7050e-01, -3.3361e-01, -1.4179e-01,  1.1261e+00,
          3.6874e-01, -1.5912e-01,  3.4773e-01, -5.5760e-01,  7.2339e-01,
          4.5633e-01,  1.0608e+00,  4.0981e-01,  2.9741e-01, -8.4885e-01,
          8.0644e-01, -1.0863e+00, -1.6227e-03,  2.0534e-01, -5.9055e-01,
         -3.5078e-01, -2.4339e-01, -2.0736e+00, -1.1567e+00, -5.9910e-01],
        [ 7.8575e-01, -1.2328e+00, -2.5935e-01, -3.3124e-01, -3.9300e-01,
         -4.1494e-01,  1.2221e+00,  7.1813e-01, -7.1843e-01,  1.6760e-01,
         -2.3116e+00,  8.0455e-01,  2.6679e-01, -1.1725e+00, -8.2101e-02,
          4.0586e-02, -1.3749e+00,  4.5029e-01,  9.8573e-01, -1.0218e+00,
         -8.3503e-01,  8.7831e-01,  1.4809e+00, -2.3377e-01,  2.9888e-01,
          1.6616e+00,  5.8521e-01,  4.3803e-01,  2.1187e-01, -7.4943e-02,
          1.2899e+00,  8.6484e-01,  1.5769e-02,  1.6439e+00,  9.0315e-01,
          9.1314e-01,  3.4006e-01, -1.0907e+00,  1.7191e-01,  2.5115e-02,
          4.6007e-01, -1.1416e+00, -2.5144e-01, -7.2468e-02,  3.7134e-01,
         -1.3163e-01, -2.5492e-01,  5.0969e-01, -8.0904e-01,  4.4991e-01],
        [-1.7138e-01,  3.0501e-01, -5.4324e-02,  6.1367e-01, -2.0930e-01,
          7.3914e-01,  1.4463e+00,  1.2427e+00, -4.7335e-01, -3.7610e-01,
         -6.4225e-01,  1.7882e+00,  3.7278e-01,  5.8581e-01, -6.6652e-01,
         -8.2386e-01, -1.3917e+00, -4.7757e-01, -1.4824e+00,  3.5371e-01,
         -6.8960e-02,  1.4582e-01, -5.4502e-01,  1.4535e+00, -2.5662e+00,
         -2.1318e-01,  3.3351e-01,  1.3449e+00, -4.5670e-01,  1.5500e-01,
          9.6947e-01,  1.0144e+00, -9.7884e-01, -8.9760e-01,  9.9870e-01,
         -4.8589e-01,  1.2717e+00, -1.1814e+00, -8.5580e-01,  5.1846e-01,
         -1.3663e+00, -1.1278e-01, -3.7446e-02, -1.1927e-01, -2.9649e+00,
         -5.3272e-01, -1.4957e+00,  3.2749e-01, -5.7097e-01,  9.4965e-01],
        [-9.3574e-02,  1.7680e-01, -4.5665e-01,  8.4989e-01,  1.7543e-01,
         -9.8662e-01, -1.6838e+00, -6.6091e-01, -1.5024e-01, -4.3033e-01,
          8.0877e-01,  9.0767e-01, -8.4638e-01, -7.6543e-01,  1.0576e+00,
          1.3402e+00, -1.4251e-01,  3.9076e-01, -8.9591e-01, -2.0071e-01,
          1.9234e-01, -1.3079e+00,  4.7949e-01, -2.1993e-02,  2.9715e-01,
          2.3297e-01,  1.7538e+00, -4.6532e-01, -1.2236e-01, -1.0223e-01,
          1.2735e+00, -2.5163e-01,  2.0971e-01,  1.0191e+00,  5.4443e-01,
          1.4750e+00, -1.0720e+00, -4.5438e-01,  3.7859e-01, -5.6359e-02,
         -2.2952e-01,  1.6525e+00, -1.0510e+00,  1.8433e+00, -5.7198e-01,
         -1.0763e+00, -1.3925e+00,  3.3712e-01, -1.0970e+00, -4.4689e-01]],
       grad_fn=<EmbeddingBackward0>)

In [54]:
# pass a to RNN
y = nn.RNN(50, 64)
y(a)

(tensor([[-0.7040, -0.9314,  0.0741,  0.0077,  0.7504, -0.1132,  0.1083,  0.7786,
           0.6258, -0.6420,  0.0088,  0.0765, -0.1437, -0.1037,  0.1155, -0.1899,
          -0.2021,  0.1992, -0.1137,  0.2365, -0.0367,  0.0278,  0.7363,  0.2932,
           0.0283, -0.6160, -0.2954, -0.5248, -0.0421, -0.4646,  0.4780, -0.7373,
           0.0935, -0.6667,  0.4280, -0.4415, -0.6290, -0.0988,  0.3242,  0.3705,
          -0.1052, -0.0518, -0.2714,  0.1657, -0.3450,  0.1493,  0.6060,  0.5957,
          -0.1814,  0.5313, -0.8127, -0.2346, -0.6982, -0.0517,  0.6013,  0.3790,
           0.7605, -0.5846, -0.4390,  0.6628,  0.8923,  0.7848, -0.6218,  0.8698],
         [-0.0201,  0.0301, -0.1349, -0.0869, -0.4851,  0.4822, -0.0801,  0.6735,
           0.5846,  0.4130,  0.0567,  0.4999, -0.6614, -0.1685, -0.2273,  0.2973,
           0.7094, -0.1304,  0.7451,  0.0194, -0.4652,  0.1721,  0.6252, -0.4003,
           0.9004, -0.7517, -0.2790, -0.2611,  0.1036, -0.6107, -0.6646, -0.2359,
           0.1935,  0.0016,  0.6362,  0.0722, -0.7817,  0.1370, -0.5811,  0.2012,
           0.3730,  0.1539,  0.6382,  0.2509, -0.1435,  0.3121, -0.5349, -0.6485,
           0.2618, -0.3065,  0.5215, -0.6783,  0.1443, -0.5968, -0.6751,  0.7112,
           0.0222,  0.0808,  0.6529, -0.2019,  0.1477,  0.5306,  0.0754,  0.1488],
         [ 0.7813,  0.0528, -0.7257,  0.1091, -0.6848,  0.7602, -0.5059, -0.0339,
          -0.0078,  0.7336, -0.5765, -0.3366, -0.1835, -0.5603, -0.2021, -0.0026,
          -0.3251, -0.3577,  0.7816,  0.6956,  0.7191, -0.1131, -0.0579,  0.0761,
          -0.3648, -0.2208,  0.7044, -0.1388,  0.6674,  0.5704, -0.1811, -0.1144,
           0.1677,  0.8039, -0.2017,  0.2798,  0.5476,  0.9247, -0.2027, -0.4916,
           0.5588, -0.2103,  0.0941,  0.7005, -0.6371, -0.1049,  0.0608, -0.3132,
          -0.0863,  0.4547, -0.0087,  0.3058, -0.5556,  0.0592,  0.0933,  0.5172,
          -0.2433,  0.6020,  0.1531, -0.3773, -0.0986, -0.2243, -0.7928, -0.7628],
         [-0.2872, -0.0641,  0.1272,  0.1421,  0.2490, -0.1516, -0.3113,  0.0573,
          -0.5467,  0.0705,  0.2817,  0.5091,  0.6931, -0.4648,  0.5796,  0.5059,
          -0.4291, -0.2524,  0.0650,  0.0013, -0.5291,  0.5607,  0.0437,  0.4402,
           0.0385, -0.1344, -0.3065,  0.1137,  0.1402,  0.0219,  0.4186, -0.3138,
          -0.1904, -0.8803,  0.3880, -0.2739, -0.6442,  0.2735, -0.2861,  0.0337,
           0.1338,  0.1257, -0.6901, -0.1456, -0.3401,  0.6325, -0.0498,  0.7342,
           0.3887, -0.4675, -0.5618,  0.3702, -0.2470,  0.5512,  0.5094,  0.1341,
          -0.0422, -0.0996,  0.6923,  0.6467, -0.7066, -0.1535, -0.4705,  0.0516],
         [ 0.2461, -0.1975, -0.4586, -0.3053, -0.1977,  0.5358, -0.5966, -0.7040,
           0.3227, -0.0879, -0.7996, -0.5376, -0.3663,  0.3568,  0.1489,  0.1131,
          -0.4899,  0.4198, -0.0919, -0.5842, -0.5694,  0.5350,  0.4416, -0.1078,
           0.2180,  0.0537, -0.5396,  0.4371, -0.5191,  0.0644, -0.7038, -0.6451,
          -0.3765, -0.2532, -0.6805,  0.2914,  0.3746,  0.1470, -0.1107,  0.2018,
           0.0966,  0.2553,  0.6993,  0.6316, -0.4687, -0.1670, -0.1582,  0.2712,
           0.6708,  0.2336, -0.3133,  0.0244, -0.3808,  0.0211, -0.2350, -0.2944,
           0.7490,  0.6024, -0.1625, -0.3251, -0.0508,  0.8156,  0.0655, -0.0134],
         [-0.3584, -0.7697, -0.0242,  0.1670,  0.6145, -0.2319,  0.1785,  0.6306,
           0.4656,  0.3052, -0.4179, -0.0942, -0.2128, -0.0290, -0.2039, -0.3064,
          -0.3611, -0.2079, -0.0266,  0.5494, -0.5113,  0.5661,  0.6317, -0.3617,
           0.0753,  0.2776, -0.6286, -0.8373,  0.2320, -0.6315, -0.3305, -0.2875,
           0.2582,  0.7923, -0.2872, -0.7606, -0.0924,  0.4621, -0.2944,  0.7770,
          -0.2506,  0.5472,  0.4106,  0.0138, -0.3825,  0.5819, -0.0295, -0.3052,
           0.2779,  0.6059,  0.2872, -0.0851, -0.4208, -0.0730, -0.1153,  0.7700,
           0.6789, -0.1075, -0.4664,  0.4672,  0.5196,  0.3963, -0.7790,  0.7270]],
        grad_fn=<SqueezeBackward1>),
 tensor([[-0.3584, -0.7697, -0.0242,  0.1670,  0.6145, -0.2319,  0.1785,  0.6306,
           0.4656,  0.3052, -0.4179, -0.0942, -0.2128, -0.0290, -0.2039, -0.3064,
          -0.3611, -0.2079, -0.0266,  0.5494, -0.5113,  0.5661,  0.6317, -0.3617,
           0.0753,  0.2776, -0.6286, -0.8373,  0.2320, -0.6315, -0.3305, -0.2875,
           0.2582,  0.7923, -0.2872, -0.7606, -0.0924,  0.4621, -0.2944,  0.7770,
          -0.2506,  0.5472,  0.4106,  0.0138, -0.3825,  0.5819, -0.0295, -0.3052,
           0.2779,  0.6059,  0.2872, -0.0851, -0.4208, -0.0730, -0.1153,  0.7700,
           0.6789, -0.1075, -0.4664,  0.4672,  0.5196,  0.3963, -0.7790,  0.7270]],
        grad_fn=<SqueezeBackward1>))

In [59]:
y(a)[0].shape # Outputs o1, o2, o3, o4, o5, o6 Hidden States one after each time step

torch.Size([6, 64])

In [61]:
b = y(a)[1]
y(a)[1].shape # Final output from RNN

torch.Size([1, 64])

In [63]:
# send final output of RNN to FC Layer
z = nn.Linear(64, len(vocab))
z(b)

tensor([[-1.4381e-01, -3.2791e-01,  1.8895e-01, -1.4841e-01,  1.7153e-01,
         -4.3273e-01,  1.3513e-01, -2.2851e-02,  2.7803e-01,  2.2004e-01,
          4.9429e-02,  6.8505e-02, -1.6752e-01, -2.8888e-01, -1.3402e-01,
          5.5633e-01,  3.6930e-02, -6.2164e-02, -3.8009e-01,  5.2007e-01,
         -1.5454e-01, -3.3636e-01, -5.4472e-01,  8.5189e-01,  3.5697e-01,
         -4.3598e-01,  5.4630e-02,  5.5763e-01, -1.7627e-01, -7.4644e-02,
          1.3781e-01, -4.1716e-01, -4.5293e-02, -7.4606e-02, -3.7268e-01,
         -1.9378e-01, -1.9878e-01,  9.2432e-02, -6.9958e-01,  2.1003e-01,
         -1.2528e-01, -1.4050e-01, -2.7490e-01,  9.3842e-04, -5.6583e-01,
          4.1692e-01, -1.3176e-01,  1.9863e-01, -1.8566e-01, -1.6762e-01,
          2.4905e-01, -1.2081e-01, -1.4267e-01, -1.2773e-01, -2.4096e-02,
         -1.9329e-01,  2.6130e-01, -3.8974e-01, -1.9920e-02, -9.6180e-02,
          6.1497e-01,  1.7024e-01, -1.2480e-01,  2.2202e-04,  2.9790e-01,
          2.7844e-01, -5.3512e-01, -2.7654e-01, -2.0062e-02, -3.1201e-01,
         -1.6398e-01, -1.1045e-01,  1.9340e-01, -1.2031e-01,  5.3331e-01,
         -1.1452e-02, -8.4753e-02, -4.2978e-01,  3.7370e-01, -1.9178e-01,
         -1.0703e-01, -2.2238e-01,  3.3727e-01, -3.1597e-01, -4.2363e-01,
         -3.0156e-01,  3.7332e-01, -1.5651e-02,  4.2151e-02,  2.0928e-01,
          1.4187e-01,  1.7258e-01,  1.2764e-01, -8.9110e-01,  1.1364e-01,
         -3.2699e-02,  3.1200e-01, -5.3139e-01,  1.7551e-01, -7.3278e-01,
         -1.0188e-01, -3.7065e-01, -1.3278e-01,  1.8675e-01, -6.2993e-03,
          4.2243e-01,  1.2471e-01, -1.5826e-01,  5.0464e-01, -3.0819e-01,
         -1.7634e-01,  2.8793e-01, -4.1755e-02, -5.6666e-04, -4.6919e-02,
         -4.6769e-02,  1.6113e-01,  1.3886e-02, -1.8606e-01, -1.9423e-01,
          1.5328e-01, -1.2061e-01,  4.6080e-02, -1.2740e-02, -1.8178e-01,
         -2.6558e-01,  5.9271e-01,  2.2192e-01,  5.1617e-01, -4.3037e-02,
          3.0292e-02, -1.5670e-01, -1.6851e-01, -1.0178e-01,  4.5650e-02,
          4.0832e-01, -4.9980e-01,  9.8115e-02, -3.3370e-01,  1.5630e-01,
          1.8787e-01,  2.1814e-01,  2.3531e-01, -1.4655e-01, -1.3642e-01,
         -1.8752e-01,  2.0426e-01, -3.1587e-01, -1.6460e-01,  1.1320e-01,
         -3.7414e-01, -3.3410e-01, -2.7548e-01, -1.2608e-01,  1.2027e-01,
          5.5786e-01,  2.8310e-01,  1.4625e-01, -1.6377e-01, -3.5082e-01,
         -1.0179e-01,  1.1416e-01,  6.7594e-02,  1.8591e-01,  2.7483e-01,
         -1.5994e-01, -1.6447e-01,  5.3698e-02, -2.9841e-01,  3.9220e-02,
         -4.1663e-02, -1.0282e-01, -3.7476e-01,  2.7630e-01, -5.9897e-01,
          1.4473e-01, -3.1336e-01, -1.6548e-01,  4.2430e-02,  4.1420e-01,
         -4.5265e-02,  5.3776e-02, -3.6430e-01, -3.7371e-01, -4.6345e-01,
          5.5481e-01,  2.1424e-01,  3.4572e-02,  7.5682e-02, -8.2715e-02,
         -3.3070e-01,  3.1798e-01, -4.8572e-01,  1.7293e-01,  2.2750e-01,
          2.0095e-01,  2.3831e-01,  3.3752e-01, -2.8006e-01, -5.9325e-01,
         -3.0182e-02,  2.9247e-01,  2.1929e-01, -3.0659e-01, -1.0009e-01,
         -4.0228e-01,  1.8829e-01,  1.6494e-01,  1.3391e-01, -1.3361e-01,
         -3.9952e-01,  3.3443e-01,  3.1706e-01, -9.2781e-02, -1.0776e-01,
          3.4646e-01, -8.1619e-02,  3.0948e-01,  1.0718e-01, -1.3045e-01,
         -3.8373e-01,  1.9061e-01, -1.4468e-01,  2.4503e-01, -2.3917e-01,
          2.3870e-01,  6.1266e-01,  6.1782e-01, -4.8993e-01, -9.7774e-02,
          6.1666e-01,  2.3367e-01, -9.8098e-02, -2.2630e-01, -1.8468e-02,
         -4.5501e-01, -1.6309e-01,  2.5736e-01,  5.2148e-02, -4.4494e-01,
         -2.1492e-02, -2.8636e-01,  3.9024e-01,  8.3712e-02, -1.4544e-01,
          7.2277e-02, -1.2297e-01, -3.0720e-01, -2.5611e-01, -3.8633e-01,
          2.8479e-01,  5.2005e-01, -4.3202e-03, -1.2657e-02, -5.0517e-02,
         -5.4397e-02, -8.0868e-02,  5.7708e-01, -1.4042e-01,  1.4884e-01,
          7.8546e-02, -8.2970e-02,  1.1384e-01,  2.8742e-01, -4.7534e-01,
         -4.8145e-02,  1.3674e-01,  9.9338e-02, -1.6080e-02, -8.2748e-02,
          1.0307e-01, -3.8369e-03, -3.2772e-01, -3.0289e-03,  2.6584e-01,
          4.2176e-01,  1.2587e-01, -5.5749e-02,  5.8279e-01, -3.4974e-01,
          2.1075e-01,  1.8962e-01,  4.0182e-01, -3.8731e-01,  6.1975e-01,
          3.6021e-01,  7.3982e-02, -9.2017e-02, -1.4676e-01, -2.9410e-01,
          4.3629e-01,  1.3686e-01,  3.3861e-01,  1.4949e-01,  1.2982e-01,
         -4.2370e-02, -1.0728e-01, -1.7297e-01,  2.2912e-01,  4.0716e-02,
         -5.2599e-02,  9.3426e-02, -4.8898e-02, -1.3024e-02, -5.0233e-01,
         -2.0031e-01,  6.4471e-03,  3.2704e-01,  2.4824e-01, -1.2976e-01,
          3.2977e-01, -1.9537e-01, -3.9917e-02,  1.7941e-01,  5.3396e-02,
         -3.3750e-01,  4.6399e-02, -3.5094e-01,  3.0450e-01, -4.4305e-01,
          5.3343e-02,  5.2628e-01, -2.1356e-01,  4.4774e-01]],
       grad_fn=<AddmmBackward0>)

In [64]:
z(b).shape

torch.Size([1, 324])

## Training Process

In [72]:
####Debugging
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])

In [85]:
learning_rate = 0.01
epochs = 20

In [86]:
model = SimpleRNN(len(vocab))

In [87]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

In [88]:
# training loop
for epoch in range(epochs):
  total_loss = 0
  for question, answer in dataloader:
    optimizer.zero_grad()

    # forward pass
    output = model(question)

    # calculate loss
    loss = criterion(output, answer[0])

    # back prop
    loss.backward()

    # update
    optimizer.step()

    total_loss += loss.item()

  print(f"Epochs: {epoch}, Loss: {total_loss:4f}")

Epochs: 0, Loss: 540.139019
Epochs: 1, Loss: 339.298120
Epochs: 2, Loss: 144.944890
Epochs: 3, Loss: 61.078041
Epochs: 4, Loss: 38.320868
Epochs: 5, Loss: 32.828745
Epochs: 6, Loss: 26.657410
Epochs: 7, Loss: 21.890049
Epochs: 8, Loss: 13.538467
Epochs: 9, Loss: 12.841703
Epochs: 10, Loss: 11.667822
Epochs: 11, Loss: 7.625669
Epochs: 12, Loss: 5.223808
Epochs: 13, Loss: 6.598932
Epochs: 14, Loss: 10.092472
Epochs: 15, Loss: 5.038844
Epochs: 16, Loss: 10.149715
Epochs: 17, Loss: 3.942872
Epochs: 18, Loss: 0.764561
Epochs: 19, Loss: 0.436354

In [96]:
def predict(model, question, threshold=0.5):

  # convert question to numbers
  numerical_question = text_to_indices(question, vocab)

  # tensor
  question_tensor = torch.tensor(numerical_question).unsqueeze(0)

  # send to model
  output = model(question_tensor)

  # convert logits to probs
  probs = torch.nn.functional.softmax(output, dim=1)

  # find index of max prob
  value, index = torch.max(probs, dim=1)

  if value < threshold:
    print("I don't know")
    return

  print(value, index)
  print(list(vocab.keys())[index])

In [97]:
predict(model, "What is the largest planet in our solar system?")

tensor([0.9922], grad_fn=<MaxBackward0>) tensor([23])
jupiter

In [98]:
predict(model, "Who is Anirban?")

I don't know