In [1]:
import numpy as np
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [3]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [4]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [5]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [6]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

## 1. Working with Dates

In [7]:
# converting to datetime datatype from object
date['date'] = pd.to_datetime(date['date'])

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

### 1. Extract year

In [9]:
date['date_year'] = date['date'].dt.year
date.sample(2)

          date  product_id  city_id  orders  date_year
134 2019-11-17        6049       16       1       2019
659 2019-06-01        3140       26       2       2019

### 2. Extract Month

In [12]:
date['date_month_no'] = date['date'].dt.month
date.sample(2)

          date  product_id  city_id  orders  date_year  date_month_no
603 2018-12-11        7435       22       2       2018             12
360 2019-03-23         435        7       2       2019              3

In [14]:
date['date_month_name'] = date['date'].dt.month_name()
date.sample(2)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
508,2019-08-17,77,25,1,2019,8,August
612,2019-01-26,7354,25,2,2019,1,January

### 3. Extract Days

In [16]:
date['date_day'] = date['date'].dt.day
date.sample()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
143,2018-08-09,5284,25,8,2018,8,August,9

### 4. Date of week

In [19]:
date['date_dow'] = date['date'].dt.dayofweek
date.sample(2)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow
104,2018-09-12,6134,6,1,2018,9,September,12,2
573,2018-12-16,5778,24,1,2018,12,December,16,6

In [22]:
date['date_dow_name'] = date['date'].dt.day_name()
date.sample(2)

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
179,2019-01-15,4571,22,3,2019,1,January,15,1,Tuesday
613,2019-04-20,7430,1,2,2019,4,April,20,5,Saturday

In [23]:
date.drop(columns = ['product_id', 'city_id', 'orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

### 5. Check if weekend

In [26]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1, 0)

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

### 6. Extract week of the year

In [29]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).sample(2)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week
971,2019-04-17,2019,4,April,17,2,Wednesday,0,16
466,2018-12-11,2018,12,December,11,1,Tuesday,0,50

### 7. Extract Quarter

In [32]:
date['quarter'] = date['date'].dt.quarter

date.drop(columns=['product_id','city_id','orders']).sample(2)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
621,2018-10-12,2018,10,October,12,4,Friday,0,41,4
498,2018-08-07,2018,8,August,7,1,Tuesday,0,32,3

### 8. Extract Semester

In [33]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)

date.drop(columns=['product_id','city_id','orders']).sample(2)

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
530,2018-08-22,2018,8,August,22,2,Wednesday,0,34,3,2
310,2018-11-20,2018,11,November,20,1,Tuesday,0,47,4,2

### 9. Extract Time elapsed between Dates

In [34]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 7, 27, 12, 57, 25, 103641)

In [35]:
today - date['date']

0     2421 days 12:57:25.103641
1     2903 days 12:57:25.103641
2     2834 days 12:57:25.103641
3     2536 days 12:57:25.103641
4     2759 days 12:57:25.103641
                 ...
995   2849 days 12:57:25.103641
996   2790 days 12:57:25.103641
997   2638 days 12:57:25.103641
998   2703 days 12:57:25.103641
999   2477 days 12:57:25.103641
Name: date, Length: 1000, dtype: timedelta64[ns]

In [36]:
# days passed
(today-date['date']).dt.days

0      2421
1      2903
2      2834
3      2536
4      2759
       ...
995    2849
996    2790
997    2638
998    2703
999    2477
Name: date, Length: 1000, dtype: int64

In [55]:
# Months passed (Not supporting)
np.round((today -date['date']) / np.timedelta64(1, 'M'),0)

ValueError: Unit M is not supported. Only unambiguous timedelta values durations are supported. Allowed units are 'W', 'D', 'h', 'm', 's', 'ms', 'us', 'ns'

## 2. Working with Time

In [44]:
time.sample(2)

                    date                                                msg
110  2012-12-12 01:23:00                  ХОЛОСТЯК ИЩЕТ ДЕВУШКУ. 0935322713
416  2014-04-11 22:47:00  . М 37л. Ищет д/ж. Для жизни ! Т 093 5000 297....

In [43]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [45]:
# Converting to datetime datatype
time['date'] = pd.to_datetime(time['date'])

In [46]:
time['hours'] = time['date'].dt.hour
time['minutes'] = time['date'].dt.minute
time['seconds'] = time['date'].dt.second

time.head()

,date,msg,hours,minutes,seconds
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

### Extract Time Part

In [47]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hours,minutes,seconds,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

### Time Difference

In [48]:
today - time['date']

0     4607 days 12:07:25.103641
1     4471 days 13:17:25.103641
2     4957 days 12:36:25.103641
3     4259 days 12:26:25.103641
4     4656 days 13:46:25.103641
                 ...
995   5246 days 12:07:25.103641
996   4567 days 13:43:25.103641
997   5032 days 13:20:25.103641
998   5148 days 13:23:25.103641
999   4420 days 13:32:25.103641
Name: date, Length: 1000, dtype: timedelta64[ns]

In [49]:
# in seconds

(today - time['date'])/np.timedelta64(1, 's')

0      3.980884e+08
1      3.863422e+08
2      4.283302e+08
3      3.680224e+08
4      4.023280e+08
           ...
995    4.532980e+08
996    3.946382e+08
997    4.348128e+08
998    4.448354e+08
999    3.819367e+08
Name: date, Length: 1000, dtype: float64

In [53]:
# in minutes
(today - time['date'])/np.timedelta64(1, 'm')

0      6.634807e+06
1      6.439037e+06
2      7.138836e+06
3      6.133706e+06
4      6.705466e+06
           ...
995    7.554967e+06
996    6.577303e+06
997    7.246880e+06
998    7.413923e+06
999    6.365612e+06
Name: date, Length: 1000, dtype: float64

In [56]:
# in hours
(today - time['date'])/np.timedelta64(1, 'h')

0      110580.123640
1      107317.290307
2      118980.606973
3      102228.440307
4      111757.773640
           ...
995    125916.123640
996    109621.723640
997    120781.340307
998    123565.390307
999    106093.540307
Name: date, Length: 1000, dtype: float64